export const LOAD_BOOKS = "LOAD_BOOKS";
export const LOAD_CATAGORY = "LOAD_CATAGORY";
export const CATAGORYWISE_BOOK = "CATAGORYWISE_BOOK";
export const STORE_TOKEN = "STORE_TOKEN";
export const CHECK_LOGIN = "CHECK_LOGIN";
export const SEND_FEEDBACK = "SEND_FEEDBACK";
export const BOOK_LOADING = "BOOK_LOADING";
export const CATAGORY_LOADING = "CATAGORY_LOADING";
export const AUTH_LOADING = "AUTH_LOADING";
export const FEEDBACK_LOADING = "FEEDBACK_LOADING";

export const LOGOUT = "LOGOUT"
